name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ] 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  # Checkout your code from GitHub

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Adjust if your project requires a different version

      - name: Install npm dependencies
        run: npm install

      - name: Build for production
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3  # Action for deployment
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          publish_dir: ./build  # Path to your production build folder

